var teams = {
  fsu: {
    name: "Florida State",
    conf: "ACC",
    wins: 2,
    losses: 0,
    sched: [
      gameDays.week1[2] + " <b>vs Oklahoma State, WIN (37-31)</b>",
      gameDays.week2[2] + " <b>vs Citadel, WIN (37-12)</b>",
      null,
      gameDays.week4[2] + " <b>vs #23 Clemson</b>",
      gameDays.week5[2] + " <b>at North Carolina State</b>",
      gameDays.week6[2] + " <b>vs Wake Forest</b>",
      gameDays.week7[2] + " <b>at Syracuse</b>",
      gameDays.week8[3] + " <b>vs #9 Notre Dame</b>",
      null,
      gameDays.week10[0] + " <b>at Louisville</b>",
      gameDays.week11[4] + " <b>vs Virginia</b>",
      gameDays.week12[4] + " <b>at Miami</b>",
      gameDays.week13[4] + " <b>vs Boston College</b>",
      gameDays.week14[3] + " <b>vs Florida</b>"
    ]
  },
  bama: {
    name: "Alabama",
    conf: "SEC",
    wins: 2,
    losses: 0,
    sched: [
      gameDays.week1[2] + " <b>vs West Virginia, WIN (33-23)</b>",
      gameDays.week2[2] + " <b>vs Florida International, WIN (41-0)</b>",
      gameDays.week3[2] + " <b>vs Southern Mississippi, WIN (52-12)</b>",
      gameDays.week4[2] + " <b>vs Florida</b>",
      null,
      gameDays.week6[2] + " <b>at #10 Ole Miss</b>",
      gameDays.week7[2] + " <b>at Arkansas</b>",
      gameDays.week8[3] + " <b>vs #6 Texas A&M</b>",
      gameDays.week9[3] + " <b>at Tennessee</b>",
      null,
      gameDays.week11[4] + " <b>at #8 LSU</b>",
      gameDays.week12[4] + " <b>vs Mississippi State</b>",
      gameDays.week13[4] + " <b>vs Western Carolina</b>",
      gameDays.week14[3] + " <b>vs #5 Auburn</b>"
    ]
  },
  oregon: {
    name: "Oregon",
    conf: "PAC12",
    wins: 2,
    losses: 0,
    sched: [
      gameDays.week1[2] + " <b>vs South Dakota, WIN (62-13)</b>",
      gameDays.week2[2] + " <b>vs #7 Michigan State, WIN (46-27)</b>",
      gameDays.week3[2] + " <b>vs Wyoming, WIN (48-14)</b>",
      gameDays.week4[2] + " <b>at Washington State</b>",
      null,
      gameDays.week6[0] + " <b>vs Arizona</b>",
      gameDays.week7[2] + " <b>at #12 UCLA</b>",
      gameDays.week8[3] + " <b>vs Washington</b>",
      gameDays.week9[2] + " <b>at California</b>",
      gameDays.week10[2] + " <b>vs #16 Stanford</b>",
      gameDays.week11[4] + " <b>at Utah</b>",
      null,
      gameDays.week13[4] + " <b>vs Colorado</b>",
      gameDays.week14[3] + " <b>at Oregon State</b>"
    ]
  },
  oklahoma: {
    name: "Oklahoma",
    conf: "BIG12",
    wins: 2,
    losses: 0,
    sched: [
      gameDays.week1[2] + " <b>vs Louisana Tech, WIN (48-16)</b>",
      gameDays.week2[2] + " <b>at Tulsa, WIN (52-7)</b>",
      gameDays.week3[2] + " <b>vs Tennessee, WIN (34-10)</b>",
      gameDays.week4[2] + " <b>at West Virginia</b>",
      null,
      gameDays.week6[2] + " <b>at TCU</b>",
      gameDays.week7[2] + " <b>vs Texas</b>",
      gameDays.week8[3] + " <b>vs #20 Kansas State</b>",
      null,
      gameDays.week10[2] + " <b>at Iowa State</b>",
      gameDays.week11[4] + " <b>vs #7 Baylor</b>",
      gameDays.week12[4] + " <b>at Texas Tech</b>",
      gameDays.week13[4] + " <b>vs Kansas</b>",
      gameDays.week14[1] + " <b>vs #25 Oklahoma State</b>"
    ]
  },
  ohiostate: {
    name: "Ohio State",
    conf: "BIG10",
    wins: 2,
    losses: 1,
    sched: [
      gameDays.week1[2] + " <b>at Navy, WIN (34-17)</b>",
      gameDays.week2[2] + " <b>vs Virginia Tech, LOSS (21-35)</b>",
      gameDays.week3[2] + " <b>vs Kent State, WIN (66-0)</b>",
      null,
      gameDays.week5[2] + " <b>at Cincinatti</b>",
      gameDays.week6[2] + " <b>at Maryland</b>",
      null,
      gameDays.week8[3] + " <b>vs Rutgers</b>",
      gameDays.week9[3] + " <b>at Penn State</b>",
      gameDays.week10[2] + " <b>vs Illinois</b>",
      gameDays.week11[4] + " <b>at #11 Michigan State</b>",
      gameDays.week12[4] + " <b>at Minnesota</b>",
      gameDays.week13[4] + " <b>vs Indiana</b>",
      gameDays.week14[3] + " <b>vs Michigan</b>"
    ]
  },
  auburn: {
    name: "Auburn",
    conf: "SEC",
    wins: 2,
    losses: 0,
    sched: [
      gameDays.week1[2] + " <b>vs Arkansas, WIN (45-21)</b>",
      gameDays.week2[2] + " <b>vs San Jose State, WIN (59-13)</b>",
      null,
      gameDays.week4[0] + " <b>at #20 Kansas State</b>",
      gameDays.week5[2] + " <b>vs Louisana Tech</b>",
      gameDays.week6[2] + " <b>vs #8 LSU</b>",
      gameDays.week7[2] + " <b>at Mississippi State</b>",
      null,
      gameDays.week9[3] + " <b>vs #14 South Carolina</b>",
      gameDays.week10[2] + " <b>at #10 Ole Miss</b>",
      gameDays.week11[4] + " <b>vs #6 Texas A&M</b>",
      gameDays.week12[4] + " <b>at #13 Georgia</b>",
      gameDays.week13[4] + " <b>vs Samford</b>",
      gameDays.week14[3] + " <b>at #3 Alabama</b>"
    ]
  },
  ucla: {
    name: "UCLA",
    conf: "PAC12",
    wins: 2,
    losses: 0,
    sched: [
      gameDays.week1[2] + " <b>at Virginia, WIN (28-20)</b>",
      gameDays.week2[2] + " <b>vs Memphis, WIN (42-35)</b>",
      gameDays.week3[2] + " <b>vs Texas, WIN (20-17)</b>",
      null,
      gameDays.week5[0] + " <b>at #15 Arizona State</b>",
      gameDays.week6[2] + " <b>vs Utah</b>",
      gameDays.week7[2] + " <b>vs #2 Oregon</b>",
      gameDays.week8[3] + " <b>at California</b>",
      gameDays.week9[3] + " <b>at Colorado</b>",
      gameDays.week10[2] + " <b>vs Arizona</b>",
      gameDays.week11[4] + " <b>at Washington</b>",
      null,
      gameDays.week13[4] + " <b>at #17 USC</b>",
      gameDays.week14[2] + " <b>vs #16 Stanford</b>"
    ]
  },
  michiganstate: {
    name: "Michigan State",
    conf: "BIG10",
    wins: 1,
    losses: 1,
    sched: [
      gameDays.week1[1] + " <b>vs Jacksonville State, WIN (45-7)</b>",
      gameDays.week2[2] + " <b>at #3 Oregon, WIN (27-46)</b>",
      null,
      gameDays.week4[2] + " <b>vs Eastern Michigan</b>",
      gameDays.week5[2] + " <b>vs Wyoming</b>",
      gameDays.week6[2] + " <b>vs #24 Nebraska</b>",
      gameDays.week7[2] + " <b>at Purdue</b>",
      gameDays.week8[3] + " <b>at Indiana</b>",
      gameDays.week9[3] + " <b>vs Michigan</b>",
      null,
      gameDays.week11[4] + " <b>vs #23 Ohio State</b>",
      gameDays.week12[4] + " <b>at Maryland</b>",
      gameDays.week13[4] + " <b>vs Rutgers</b>",
      gameDays.week14[3] + " <b>vs Penn State</b>"
    ]
  },
  usce: {
    name: "South Carolina",
    conf: "SEC",
    wins: 1,
    losses: 1,
    sched: [
      gameDays.week1[0] + " <b>vs #21 Texas A&M, LOSS (28-52)</b>",
      gameDays.week2[2] + " <b>vs East Carolina, WIN (33-23)</b>",
      gameDays.week3[2] + " <b>vs #6 Georgia, WIN (38-35)</b>",
      gameDays.week4[2] + " <b>at Vanderbilt</b>",
      gameDays.week5[2] + " <b>vs #18 Missouri</b>",
      gameDays.week6[2] + " <b>at Kentucky</b>",
      null,
      gameDays.week8[3] + " <b>vs Furman</b>",
      gameDays.week9[3] + " <b>at #5 Auburn</b>",
      gameDays.week10[2] + " <b>vs Tennessee</b>",
      null,
      gameDays.week12[4] + " <b>at Florida</b>",
      gameDays.week13[4] + " <b>vs South Alabama</b>",
      gameDays.week14[3] + " <b>at #22 Clemson</b>"
    ]
  },
  baylor: {
    name: "Baylor",
    conf: "BIG12",
    wins: 3,
    losses: 0,
    sched: [
      gameDays.week1[3] + " <b>vs SMU, WIN (45-0)</b>",
      gameDays.week2[2] + " <b>vs Northwestern State, WIN (70-6)</b>",
      gameDays.week3[1] + " <b>at Buffalo, WIN (63-21)</b>",
      null,
      gameDays.week5[2] + " <b>at Iowa State</b>",
      gameDays.week6[2] + " <b>at Texas</b>",
      gameDays.week7[2] + " <b>vs TCU</b>",
      gameDays.week8[3] + " <b>at West Virginia</b>",
      null,
      gameDays.week10[2] + " <b>vs Kansas</b>",
      gameDays.week11[4] + " <b>at #4 Oklahoma</b>",
      null,
      gameDays.week13[4] + " <b>vs #25 Oklahoma State</b>",
      gameDays.week14[3] + " <b>vs Texas Tech</b>",
      gameDays.week15[1] + " <b>vs #20 Kansas State</b>"
    ]
  },
  stanford: {
    name: "Stanford",
    conf: "PAC12",
    wins: 1,
    losses: 1,
    sched: [
      gameDays.week1[0] + " <b>vs UC Davis, WIN (45-0)</b>",
      gameDays.week2[2] + " <b>#14 USC, LOSS (10-13)</b>",
      gameDays.week3[2] + " <b>vs Army, WIN (35-0)</b>",
      gameDays.week4[2] + " <b>at Washington</b>",
      gameDays.week5[2] + " <b>at #9 Notre Dame</b>",
      gameDays.week6[2] + " <b>vs Washington State</b>",
      gameDays.week7[2] + " <b>at #15 Arizona State</b>",
      gameDays.week8[3] + " <b>vs Oregon State</b>",
      null,
      gameDays.week10[2] + " <b>at #2 Oregon</b>",
      gameDays.week11[4] + " <b>vs Utah</b>",
      gameDays.week12[4] + " <b>at California</b>",
      null,
      gameDays.week14[1] + " <b>at #12 UCLA</b>"
    ]
  },
  uga: {
    name: "Georgia",
    conf: "SEC",
    wins: 1,
    losses: 0,
    sched: [
      gameDays.week1[2] + " <b>at #16 Clemson, WIN (45-21)</b>",
      null,
      gameDays.week3[2] + " <b>at #24 South Carolina, LOSS (35-38)</b>",
      gameDays.week4[2] + " <b>vs Troy</b>",
      gameDays.week5[2] + " <b>vs Tennessee</b>",
      gameDays.week6[2] + " <b>vs Vanderbilt</b>",
      gameDays.week7[2] + " <b>at #18 Missouri</b>",
      gameDays.week8[2] + " <b>at Arkansas</b>",
      null,
      gameDays.week10[2] + " <b>vs Florida</b>",
      gameDays.week11[4] + " <b>at Kentucky</b>",
      gameDays.week12[4] + " <b>vs #5 Auburn</b>",
      gameDays.week13[4] + " <b>vs Charleston Southern</b>",
      gameDays.week14[3] + " <b>vs Georgia Tech</b>"
    ]
  },
  lsu: {
    name: "LSU",
    conf: "SEC",
    wins: 2,
    losses: 0,
    sched: [
      gameDays.week1[2] + " <b>vs #14 Wisconsin, WIN (28-24)</b>",
      gameDays.week2[2] + " <b>vs Sam Houston, WIN (56-0)</b>",
      gameDays.week3[2] + " <b>vs UL-Monroe, WIN (31-10)</b>",
      gameDays.week4[2] + " <b>vs Mississippi State</b>",
      gameDays.week5[2] + " <b>vs New Mexico State</b>",
      gameDays.week6[2] + " <b>at #5 Auburn</b>",
      gameDays.week7[2] + " <b>at Florida</b>",
      gameDays.week8[3] + " <b>vs Kentucky</b>",
      null,
      gameDays.week10[2] + " <b>vs #10 Ole Miss</b>",
      gameDays.week11[4] + " <b>vs #3 Alabama</b>",
      gameDays.week12[4] + " <b>at Arkansas</b>",
      null,
      gameDays.week14[1] + " <b>at #6 Texas A&M</b>"
    ]
  },
  wiscy: {
    name: "Wisconsin",
    conf: "BIG10",
    wins: 1,
    losses: 1,
    sched: [
      gameDays.week1[2] + " <b>vs #13 LSU, LOSS (24-28)</b>",
      gameDays.week2[2] + " <b>vs Western Illinois, WIN (37-3)</b>",
      null,
      gameDays.week4[2] + " <b>vs Bowling Green</b>",
      gameDays.week5[2] + " <b>vs South Florida</b>",
      gameDays.week6[2] + " <b>at Northwestern</b>",
      gameDays.week7[2] + " <b>vs Illinois</b>",
      null,
      gameDays.week9[3] + " <b>vs Maryland</b>",
      gameDays.week10[2] + " <b>at Rutgers</b>",
      gameDays.week11[4] + " <b>at Purdue</b>",
      gameDays.week12[4] + " <b>vs #24 Nebraska</b>",
      gameDays.week13[4] + " <b>at Iowa</b>",
      gameDays.week14[3] + " <b>vs Minnesota</b>"
    ]
  },
  uscw: {
    name: "USC",
    conf: "PAC12",
    wins: 2,
    losses: 0,
    sched: [
      gameDays.week1[2] + " <b>vs Fresno State, WIN (52-13)</b>",
      gameDays.week2[2] + " <b>at #13 Stanford, WIN (13-10)</b>",
      gameDays.week3[2] + " <b>at Boston College, LOSS (31-37)</b>",
      null,
      gameDays.week5[2] + " <b>vs Oregon State</b>",
      gameDays.week6[2] + " <b>vs #15 Arizona State</b>",
      gameDays.week7[2] + " <b>at Arizona</b>",
      gameDays.week8[3] + " <b>vs Colorado</b>",
      gameDays.week9[3] + " <b>at Utah</b>",
      gameDays.week10[2] + " <b>at Washington State</b>",
      null,
      gameDays.week12[2] + " <b>vs California</b>",
      gameDays.week13[4] + " <b>at #12 UCLA</b>",
      gameDays.week14[3] + " <b>vs #9 Notre Dame</b>"
    ]
  },
  clemson: {
    name: "Clemson",
    conf: "ACC",
    wins: 1,
    losses: 1,
    sched: [
      gameDays.week1[2] + " <b>at #12 Georgia, LOSS (21-45)</b>",
      gameDays.week2[2] + " <b>vs South Carolina State, WIN (73-7)</b>",
      null,
      gameDays.week4[2] + " <b>at #1 Florida State</b>",
      gameDays.week5[2] + " <b>vs North Carolina</b>",
      gameDays.week6[2] + " <b>vs NC State</b>",
      gameDays.week7[2] + " <b>vs Louisville</b>",
      gameDays.week8[3] + " <b>at Boston College</b>",
      gameDays.week9[3] + " <b>vs Syracuse</b>",
      null,
      gameDays.week11[2] + " <b>at Wake Forest</b>",
      gameDays.week12[4] + " <b>at Georgia Tech</b>",
      gameDays.week13[4] + " <b>vs Georgia State</b>",
      gameDays.week14[3] + " <b>vs #14 South Carolina</b>"
    ]
  },
  notredame: {
    name: "Notre Dame",
    conf: "Independent",
    wins: 2,
    losses: 0,
    sched: [
      gameDays.week1[2] + " <b>vs Rice, WIN (48-17)</b>",
      gameDays.week2[2] + " <b>vs Michigan, WIN (31-0)</b>",
      gameDays.week3[2] + " <b>vs Purdue, WIN (30-14)</b>",
      null,
      gameDays.week5[2] + " <b>vs Syracuse</b>",
      gameDays.week6[2] + " <b>vs #16 Stanford</b>",
      gameDays.week7[2] + " <b>vs North Carolina</b>",
      gameDays.week8[3] + " <b>at #1 Florida State</b>",
      null,
      gameDays.week10[2] + " <b>at Navy</b>",
      gameDays.week11[4] + " <b>at #15 Arizona State</b>",
      gameDays.week12[4] + " <b>vs Northwestern</b>",
      gameDays.week13[4] + " <b>vs Louisville</b>",
      gameDays.week14[3] + " <b>at #17 USC</b>"
    ]
  },
  olemiss: {
    name: "Ole Miss",
    conf: "SEC",
    wins: 2,
    losses: 0,
    sched: [
      gameDays.week1[0] + " <b>vs Boise State, W (35-13)</b>",
      gameDays.week2[2] + " <b>at Vanderbilt, WIN (41-3)</b>",
      gameDays.week3[2] + " <b>vs LA-Lafayette, WIN (56-15)</b>",
      null,
      gameDays.week5[2] + " <b>vs Memphis</b>",
      gameDays.week6[2] + " <b>vs #3 Alabama</b>",
      gameDays.week7[2] + " <b>at #6 Texas A&M</b>",
      gameDays.week8[3] + " <b>vs Tennessee</b>",
      gameDays.week9[3] + " <b>at #8 LSU</b>",
      gameDays.week10[2] + " <b>vs #5 Auburn</b>",
      gameDays.week11[4] + " <b>vs Presbyterian</b>",
      null,
      gameDays.week13[4] + " <b>at Arkansas</b>",
      gameDays.week14[3] + " <b>vs Mississippi State</b>"
    ]
  },
  asu: {
    name: "Arizona State",
    conf: "PAC12",
    wins: 2,
    losses: 0,
    sched: [
      gameDays.week1[0] + " <b>vs Weber State, W (45-14)</b>",
      gameDays.week2[2] + " <b>at New Mexico, WIN (58-23)</b>",
      gameDays.week3[2] + " <b>at Colorado</b>",
      null,
      gameDays.week5[2] + " <b>vs #12 UCLA</b>",
      gameDays.week6[2] + " <b>at #17 USC</b>",
      null,
      gameDays.week8[3] + " <b>vs #16 Stanford</b>",
      gameDays.week9[3] + " <b>at Washington</b>",
      gameDays.week10[2] + " <b>vs Utah</b>",
      gameDays.week11[4] + " <b>vs #9 Notre Dame</b>",
      gameDays.week12[4] + " <b>at Oregon State</b>",
      gameDays.week13[4] + " <b>vs Washington State</b>",
      gameDays.week14[2] + " <b>at Arizona</b>"
    ]
  },
  kstate: {
    name: "Kansas State",
    conf: "BIG12",
    wins: 2,
    losses: 0,
    sched: [
      gameDays.week1[2] + " <b>at Stephen F. Austin, WIN (55-16)</b>",
      gameDays.week2[2] + " <b>at Iowa State, WIN (32-28)</b>",
      null,
      gameDays.week4[2] + " <b>vs #5 Auburn</b>",
      gameDays.week5[2] + " <b>vs UTEP</b>",
      gameDays.week6[2] + " <b>vs Texas Tech</b>",
      null,
      gameDays.week8[3] + " <b>at #4 Oklahoma</b>",
      gameDays.week9[3] + " <b>vs Texas</b>",
      gameDays.week10[2] + " <b>vs #25 Oklahoma State</b>",
      gameDays.week11[4] + " <b>at TCU</b>",
      null,
      gameDays.week13[2] + " <b>at West Virginia</b>",
      gameDays.week14[3] + " <b>vs Kansas</b>",
      gameDays.week15[1] + " <b>at #7 Baylor</b>"
    ]
  },
  texasam: {
    name: "Texas A&M",
    conf: "SEC",
    wins: 2,
    losses: 0,
    sched: [
      gameDays.week1[0] + " <b>at #9 South Carolina, W (52-28)</b>",
      gameDays.week2[2] + " <b>vs Lamar, WIN (73-3)</b>",
      gameDays.week3[2] + " <b>vs Rice, WIN (38-10)</b>",
      gameDays.week4[2] + " <b>at SMU</b>",
      gameDays.week5[2] + " <b>vs Arkansas</b>",
      gameDays.week6[2] + " <b>at Mississippi State</b>",
      gameDays.week7[2] + " <b>vs #10 Ole Miss</b>",
      gameDays.week8[3] + " <b>at #3 Alabama</b>",
      null,
      gameDays.week10[2] + " <b>vs UL-Monroe</b>",
      gameDays.week11[4] + " <b>at #5 Auburn</b>",
      gameDays.week12[4] + " <b>vs #18 Missouri</b>",
      null,
      gameDays.week14[1] + " <b>vs #8 LSU</b>"
    ]
  },
  nebraska: {
    name: "Nebraska",
    conf: "BIG10",
    wins: 2,
    losses: 0,
    sched: [
      gameDays.week1[2] + " <b>vs Florida Atlantic, WIN (55-7)</b>",
      gameDays.week2[2] + " <b>vs McNeese State, WIN (31-24)</b>",
      gameDays.week3[2] + " <b>at Fresno State, WIN (55-19)</b>",
      gameDays.week4[2] + " <b>vs Miami (FL)</b>",
      gameDays.week5[2] + " <b>vs Illinois</b>",
      gameDays.week6[2] + " <b>at #11 Michigan State</b>",
      null,
      gameDays.week8[3] + " <b>at Northwestern</b>",
      gameDays.week9[3] + " <b>vs Rutgers</b>",
      gameDays.week10[2] + " <b>vs Purdue</b>",
      null,
      gameDays.week12[4] + " <b>at #19 Wisconsin</b>",
      gameDays.week13[4] + " <b>vs Minnesota</b>",
      gameDays.week14[2] + " <b>at Iowa</b>"
    ]
  },
  unc: {
    name: "North Carolina",
    conf: "ACC",
    wins: 2,
    losses: 0,
    sched: [
      gameDays.week1[2] + " <b>vs Liberty, WIN (56-29)</b>",
      gameDays.week2[2] + " <b>vs San Diego State, WIN (31-27)</b>",
      null,
      gameDays.week4[2] + " <b>at East Carolina</b>",
      gameDays.week5[2] + " <b>at #22 Clemson</b>",
      gameDays.week6[2] + " <b>vs Virginia Tech</b>",
      gameDays.week7[2] + " <b>at #9 Notre Dame</b>",
      gameDays.week8[3] + " <b>vs Georgia Tech</b>",
      gameDays.week9[3] + " <b>at Virginia</b>",
      gameDays.week10[2] + " <b>at Miami (FL)</b>",
      null,
      gameDays.week12[4] + " <b>vs Pittsburgh</b>",
      gameDays.week13[2] + " <b>at Duke</b>",
      gameDays.week14[3] + " <b>vs NC State</b>"
    ]
  },
  mizzou: {
    name: "Missouri",
    conf: "SEC",
    wins: 2,
    losses: 0,
    sched: [
      gameDays.week1[2] + " <b>vs South Dakota State, WIN (38-18)</b>",
      gameDays.week2[2] + " <b>at Toledo, WIN (49-24)</b>",
      gameDays.week3[2] + " <b>vs UCF, WIN (38-10)</b>",
      gameDays.week4[2] + " <b>vs Indiana</b>",
      gameDays.week5[2] + " <b>at #14 South Carolina</b>",
      null,
      gameDays.week7[2] + " <b>vs #13 Georgia</b>",
      gameDays.week8[3] + " <b>at Florida</b>",
      gameDays.week9[3] + " <b>vs Vanderbilt</b>",
      gameDays.week10[2] + " <b>vs Kentucky</b>",
      null,
      gameDays.week12[4] + " <b>at #6 Texas A&M</b>",
      gameDays.week13[4] + " <b>at Tennessee</b>",
      gameDays.week14[2] + " <b>vs Arkansas</b>"
    ]
  },

  vatech: {
    name: "Virginia Tech",
    conf: "ACC",
    wins: 2,
    losses: 1,
    sched: [
      gameDays.week1[2] + " <b>vs William & Mary, WIN (34-9)</b>",
      gameDays.week2[2] + " <b>at #8 Ohio State, WIN (35-21)</b>",
      gameDays.week3[2] + " <b>vs East Carolina, LOSS (21-28)</b>",
      gameDays.week4[2] + " <b>vs Georgia Tech</b>",
      gameDays.week5[2] + " <b>vs Western Michigan</b>",
      gameDays.week6[2] + " <b>at North Carolina</b>",
      null,
      gameDays.week8[1] + " <b>at Pittsburgh</b>",
      gameDays.week9[1] + " <b>vs Miami (FL)</b>",
      gameDays.week10[2] + " <b>vs Boston College</b>",
      null,
      gameDays.week12[4] + " <b>at Duke</b>",
      gameDays.week13[4] + " <b>at Wake Forest</b>",
      gameDays.week14[2] + " <b>vs Virginia</b>"
    ]
  },

  louisville: {
    name: "Louisville",
    conf: "ACC",
    wins: 2,
    losses: 1,
    sched: [
      gameDays.week1[4] + " <b>vs Miami (FL), WIN (31-13)</b>",
      gameDays.week2[2] + " <b>vs Murray State, WIN (66-21)</b>",
      gameDays.week3[2] + " <b>at Virginia, LOSS (21-23)</b>",
      gameDays.week4[2] + " <b>at FIU</b>",
      gameDays.week5[2] + " <b>vs Wake Forest</b>",
      gameDays.week6[1] + " <b>at Syracuse</b>",
      gameDays.week7[2] + " <b>at #22 Clemson</b>",
      gameDays.week8[3] + " <b>vs NC State</b>",
      null,
      gameDays.week10[0] + " <b>vs #1 Florida State</b>",
      gameDays.week11[4] + " <b>at Boston College</b>",
      null,
      gameDays.week13[4] + " <b>at #9 Notre Dame</b>",
      gameDays.week14[3] + " <b>vs Kentucky</b>"
    ]
  },
  byu: {
      name: "BYU",
      conf: "Independent",
      wins: 3,
      losses: 0,
      sched: [
        gameDays.week1[1] + " <b>at UConn, WIN (35-10)</b>",
        gameDays.week2[2] + " <b>at Texas, WIN (41-7)</b>",
        gameDays.week3[0] + " <b>vs Houston, WIN (33-25)</b>",
        gameDays.week4[2] + " <b>vs Virginia</b>",
        null,
        gameDays.week6[1] + " <b>vs Utah State</b>",
        gameDays.week7[0] + " <b>at UCF</b>",
        gameDays.week8[3] + " <b>vs Nevada</b>",
        gameDays.week9[2] + " <b>at Boise State</b>",
        gameDays.week10[2] + " <b>at Middle Tennessee</b>",
        null,
        gameDays.week12[4] + " <b>vs UNLV</b>",
        gameDays.week13[4] + " <b>vs Savannah State</b>",
        gameDays.week13[3] + " <b>at California</b>"
      ]
    },
    osu: {
      name: "Oklahoma State",
      conf: "Big 12",
      wins: 2,
      losses: 1,
      sched: [
        gameDays.week1[2] + " <b>vs #1 Florida State, LOSS (31-37)</b>",
        gameDays.week2[2] + " <b>vs Missouri State, WIN (40-23)</b>",
        gameDays.week3[2] + " <b>vs UT San Antonio, WIN (43-13)</b>",
        null,
        gameDays.week5[0] + " <b>vs Texas Tech</b>",
        gameDays.week6[2] + " <b>vs Iowa State</b>",
        gameDays.week7[2] + " <b>at Kansas</b>",
        gameDays.week8[3] + " <b>vs TCU</b>",
        gameDays.week9[3] + " <b>vs West Virginia</b>",
        gameDays.week10[2] + " <b>at Kansas State</b>",
        null,
        gameDays.week12[4] + " <b>vs Texas</b>",
        gameDays.week13[4] + " <b>at #7 Baylor</b>",
        null,
        gameDays.week15[1] + " <b>at #4 Oklahoma</b>"
      ]
    }
};
